data:
  img_size: 640
  train_l: data_segment/train_l.txt
  train_u: data_segment/train_u.txt
  val: data_segment/val.txt
  test: data_segment/test.txt
  num_classes: 1
  num_workers: 2
train:
  epochs: 200
  batch: 8
  lr: 0.001
  lambda_seg: 1.0
  lambda_cons: 0.5
  ema_decay: 0.999
  lambda_sup: 1.0
  save_dir: outputs/checkpoints"
  save_plot: outputs/plots"

semi:
  min_conf: 0.6
